education/Controllers/HomeController.cs
using education.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace education.Controllers
{
    public  class HomeController : Controller
    {
        educationEntities m = new educationEntities();
        public ActionResult Index()
        {
            return View(); 
        }
        [ChildActionOnly]
        public ActionResult TopMenu()
        {
            
            return PartialView(m.menus.OrderBy(s => s.ordering));
        }
        [ChildActionOnly]
        public ActionResult Slider()
        {

            return PartialView(m.mediagalleries);
        }
        [ChildActionOnly]
        public ActionResult Top8News()
        {
            return PartialView(from c in m.categories
                               from x in m.contents
                               where c.parent_id == 2 && x.catid == c.id
                               select x);
        }
        [ChildActionOnly]
        public ActionResult Slogan()
        {

            return PartialView(m.contents.Find(13));
        }
        public ActionResult HomeServices()
        {

            return PartialView(m.contents.Where(db => db.catid == 3).OrderBy(db => db.ordering));
        }
    }
}

education/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using education.Models;
using PagedList;

namespace education.Controllers
{
    public class NewsController : Controller
    {
        private educationEntities db = new educationEntities();

        // GET: /News/
        public ActionResult Index()
        {
            var query = (from c in db.categories
                         from x in db.contents
                         where c.parent_id == 2 && x.catid == c.id
                         select x);
            
            return View(query);
        }
        //Category
        [Authorize]
        public ActionResult ListCategory()
        {
            var query = (from c in db.categories
                         where c.parent_id == 2 
                         select c);

            return View(query);
        }
        [Authorize]
        public ActionResult CreateCategory()
        {
            return View();
        }
        [HttpPost,Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult CreateCategory([Bind(Include = "title,note")] category category)
        {
            if (ModelState.IsValid)
            {
                category.parent_id = 2;
                db.categories.Add(category);
                db.SaveChanges();
                return RedirectToAction("ListCategory");
            }

            return View(category);
        }
        [HttpPost, Authorize]
        public JsonResult DeleteCategory(int id)
        {
            category category = db.categories.Find(id);
            var content = db.contents.Where(m => m.catid == id);
            foreach(var item in content)
            {

                db.contents.Remove(item);
            }
            db.categories.Remove(category);
            db.SaveChanges();
            return Json("Xóa thể loại thành công!");
        }
        [Authorize]
        public ActionResult EditCategory(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            category category = db.categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }
        [HttpPost, Authorize]
        public ActionResult EditCategory([Bind(Include = "id,title,note")] category category)
        {
            if (ModelState.IsValid)
            {
                category.parent_id = 2;
                db.Entry(category).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("ListCategory");
            }
            return View(category);
        }
        //News
        [Authorize]
        public ActionResult ListNews(int? page)
        {
            //int pageSize = 8;
            //int pageNumber = (page ?? 1);
            //IPagedList<content> contents = null;
            //contents = (from c in db.categories
            //            from x in db.contents
            //            where c.parent_id == 2 && x.catid == c.id
            //            select x).OrderByDescending(s => s.id).ToPagedList(pageNumber, pageSize);
            var contents = (from c in db.categories
                        from x in db.contents
                        where c.parent_id == 2 && x.catid == c.id
                        select x).OrderByDescending(s => s.id).ToList();
            return View(contents);
        }
        [Authorize]
        public ActionResult CreateNews()
        {
            var countries = new SelectList(db.categories.Where(c => c.parent_id == 2).ToArray(), "id", "title");
            ViewBag.Category = countries;
            return View();
        }
        [HttpPost, Authorize, ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult CreateNews([Bind(Include = "title,image,introtext,fulltext,catid")] content content)
        {
            if (ModelState.IsValid)
            {
                string CurrentUser = null;
                if (System.Web.HttpContext.Current.Request.IsAuthenticated)
                {
                    CurrentUser = System.Web.HttpContext.Current.User.Identity.Name;
                }
                content.create_by = CurrentUser;
                db.contents.Add(content);
                db.SaveChanges();
                return RedirectToAction("ListNews");
            }

            return View(content);
        }
        [HttpPost, Authorize]
        public JsonResult DeleteNews(int id)
        {
            content content = db.contents.Find(id);
            db.contents.Remove(content);
            db.SaveChanges();
            return Json("Xóa tin thành công!");
        }
        [Authorize]
        public ActionResult EditNews(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            content content = db.contents.Find(id);
            if (content == null)
            {
                return HttpNotFound();
            }
            var countries = new SelectList(db.categories.Where(c => c.parent_id == 2).ToArray(), "id", "title",content.catid);
            ViewBag.Category = countries;
            return View(content);
        }
        [HttpPost, Authorize, ValidateInput(false)]
        public ActionResult EditNews([Bind(Include = "id,title,fulltext,introtext,image,catid")] content content)
        {
            if (ModelState.IsValid)
            {
                string CurrentUser = null;
                if (HttpContext.Request.IsAuthenticated)
                {
                    CurrentUser = HttpContext.User.Identity.Name;
                }
                content.create_by = CurrentUser;
                db.Entry(content).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("ListNews");
            }
            return View(content);
        }
        // GET: /News/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            content content = db.contents.Find(id);
            if (content == null)
            {
                return HttpNotFound();
            }
            return View(content);
        }

        // GET: /News/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /News/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="id,title,introtext,fulltext,state,catid,created,create_by,image,ordering,hit")] content content)
        {
            if (ModelState.IsValid)
            {
                db.contents.Add(content);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(content);
        }

        // GET: /News/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            content content = db.contents.Find(id);
            if (content == null)
            {
                return HttpNotFound();
            }
            return View(content);
        }

        // POST: /News/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="id,title,introtext,fulltext,state,catid,created,create_by,image,ordering,hit")] content content)
        {
            if (ModelState.IsValid)
            {
                db.Entry(content).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(content);
        }

        // GET: /News/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            content content = db.contents.Find(id);
            if (content == null)
            {
                return HttpNotFound();
            }
            return View(content);
        }

        // POST: /News/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            content content = db.contents.Find(id);
            db.contents.Remove(content);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult NewsRelated(int? id)
        {
            var query = (from c in db.categories
                         from x in db.contents
                         where c.parent_id == 2 && x.catid == c.id && x.catid== id
                         select x).OrderByDescending(x => x.id).Take(4);
            return PartialView(query);
        }
        public ActionResult TypeOfNews()
        {

            return PartialView(db.categories.Where(c => c.parent_id == 2));
        }
    }
}

education/Views/Home/HomeServices.cshtml
@model IEnumerable<education.Models.content>
@{
    string updownchecker = "fadeInUp";
}
@foreach(var item in Model)
{
    <div class="col-sm-3">
        <div class="service wow @updownchecker">
            <div class="service-icon"><i class="fa @item.image"></i></div>
            <h3>@item.title</h3>
            <p>@item.introtext</p>
            <a class="big-link-1" href="services">Read more</a>
        </div>
    </div>
    if (updownchecker == "fadeInUp")
    {
        updownchecker = "fadeInDown";
    }
    else
    {
        updownchecker = "fadeInUp";
    }
}

education/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Tư vấn du học";
}

<!-- Slider -->
<div class="slider-container">
    <div class="container">
        <div class="row">
            <div class="col-sm-10 col-sm-offset-1 slider">
                <div class="flexslider">
                    @{Html.RenderAction("Slider", "Home");}
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Presentation -->
<div class="presentation-container">
    <div class="container">
        <div class="row">
            @{Html.RenderAction("Slogan", "Home");}
        </div>
    </div>
</div>

<!-- Services -->
<div class="services-container">
    <div class="container">
        <div class="row">
            @{Html.RenderAction("HomeServices");}
        </div>
    </div>
</div>

<!-- Latest work -->
<div class="work-container">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 work-title wow fadeIn">
                <h2>News and Event</h2>
            </div>
        </div>
        <div class="row">
            
            @{Html.RenderAction("Top8News", "Home");}

        </div>
    </div>
</div>

<!-- Testimonials -->
<div class="testimonials-container">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 testimonials-title wow fadeIn">
                <h2>Testimonials</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-10 col-sm-offset-1 testimonial-list">
                <div role="tabpanel">
                    <!-- Tab panes -->
                    <div class="tab-content">
                        <div role="tabpanel" class="tab-pane fade in active" id="tab1">
                            <div class="testimonial-image">
                                <img src="/assets/img/testimonials/1.jpg" alt="" data-at2x="assets/img/testimonials/1.jpg">
                            </div>
                            <div class="testimonial-text">
                                <p>
                                    "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et.
                                    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et.
                                    Lorem ipsum dolor sit amet, consectetur..."<br>
                                    <a href="#">Lorem Ipsum, dolor.co.uk</a>
                                </p>
                            </div>
                        </div>
                        <div role="tabpanel" class="tab-pane fade" id="tab2">
                            <div class="testimonial-image">
                                <img src="/assets/img/testimonials/2.jpg" alt="" data-at2x="assets/img/testimonials/2.jpg">
                            </div>
                            <div class="testimonial-text">
                                <p>
                                    "Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip
                                    ex ea commodo consequat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit
                                    lobortis nisl ut aliquip ex ea commodo consequat..."<br>
                                    <a href="#">Minim Veniam, nostrud.com</a>
                                </p>
                            </div>
                        </div>
                        <div role="tabpanel" class="tab-pane fade" id="tab3">
                            <div class="testimonial-image">
                                <img src="/assets/img/testimonials/3.jpg" alt="" data-at2x="assets/img/testimonials/3.jpg">
                            </div>
                            <div class="testimonial-text">
                                <p>
                                    "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et.
                                    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et.
                                    Lorem ipsum dolor sit amet, consectetur..."<br>
                                    <a href="#">Lorem Ipsum, dolor.co.uk</a>
                                </p>
                            </div>
                        </div>
                        <div role="tabpanel" class="tab-pane fade" id="tab4">
                            <div class="testimonial-image">
                                <img src="/assets/img/testimonials/1.jpg" alt="" data-at2x="assets/img/testimonials/1.jpg">
                            </div>
                            <div class="testimonial-text">
                                <p>
                                    "Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip
                                    ex ea commodo consequat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit
                                    lobortis nisl ut aliquip ex ea commodo consequat..."<br>
                                    <a href="#">Minim Veniam, nostrud.com</a>
                                </p>
                            </div>
                        </div>
                    </div>
                    <!-- Nav tabs -->
                    <ul class="nav nav-tabs" role="tablist">
                        <li role="presentation" class="active">
                            <a href="#tab1" aria-controls="tab1" role="tab" data-toggle="tab"></a>
                        </li>
                        <li role="presentation">
                            <a href="#tab2" aria-controls="tab2" role="tab" data-toggle="tab"></a>
                        </li>
                        <li role="presentation">
                            <a href="#tab3" aria-controls="tab3" role="tab" data-toggle="tab"></a>
                        </li>
                        <li role="presentation">
                            <a href="#tab4" aria-controls="tab4" role="tab" data-toggle="tab"></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

education/Views/Home/Slider.cshtml
@model IEnumerable<education.Models.mediagallery>
<ul class="slides">
    @foreach (var item in Model)
    {
        <li data-thumb="/content/images/slider/@item.filename">
            <img src="/content/images/slider/@item.filename">
            <div class="flex-caption">
                @item.caption
            </div>
        </li>
    }
</ul>

education/Views/Home/Slogan.cshtml
@model education.Models.content

<div class="col-sm-12 wow fadeInLeftBig">
    @Html.Raw(Server.HtmlDecode(Model.introtext))
    <p>@Model.fulltext</p>
</div>

education/Views/Home/Top8News.cshtml
@model IEnumerable<education.Models.content>
@{
    string updownchecker = "fadeInUp";
}
@foreach(var item in Model.Take(8))
{
    <div class="col-sm-3">
        <div class="work wow @updownchecker">
            <img src="@item.image" alt="@item.title" data-at2x="@item.image">
            <a href="@Url.Action("Details", "News", new { id = item.id})"><h3>@item.title</h3></a>
            <p>@item.introtext</p>
            <div class="work-bottom">
                <a class="big-link-2 view-work" href="@item.image"><i class="fa fa-search"></i></a>
                <a class="big-link-2" href="@Url.Action("Details", "News", new { id = item.id})"><i class="fa fa-link"></i></a>
            </div>
        </div>
	</div>
    if (updownchecker == "fadeInUp")
    {
        updownchecker = "fadeInDown";
    }
    else
    {
        updownchecker = "fadeInUp";
    }
}

education/Views/Home/Topmenu.cshtml
@model IEnumerable<education.Models.menu>
@using education.Helper
<ul class="nav navbar-nav navbar-right">
    @foreach (var item in Model)
    {

    <li class=@Html.MenuItem(item.link)>
        <a href="/@item.link"><i class="fa @item.note"></i><br>@item.title</a>
    </li>

    }
</ul>