education/Controllers/ServicesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using education.Models;

namespace education.Controllers
{

    public class ServicesController : Controller
    {
        private educationEntities db = new educationEntities();

        // GET: /Services/
        public ActionResult Index()
        {
            return View(db.contents.Where(c => c.catid ==3).ToList());
        }
        [Authorize]
        public ActionResult ListService()
        {
            return View(db.contents.Where(c => c.catid == 3).ToList());
        }
        [HttpPost, Authorize]
        public JsonResult DeleteService(int id)
        {
            content content = db.contents.Find(id);
            db.contents.Remove(content);
            db.SaveChanges();
            return Json("Xóa serive thành công!");
        }
        // GET: /Services/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            content content = db.contents.Find(id);
            if (content == null)
            {
                return HttpNotFound();
            }
            return View(content);
        }

        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Services/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, Authorize, ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "title,image,introtext,fulltext")] content content)
        {
            if (ModelState.IsValid)
            {
                string CurrentUser = null;
                if (System.Web.HttpContext.Current.Request.IsAuthenticated)
                {
                    CurrentUser = System.Web.HttpContext.Current.User.Identity.Name;
                }
                content.create_by = CurrentUser;
                content.catid = 3;
                db.contents.Add(content);
                db.SaveChanges();
                return RedirectToAction("ListService");
            }

            return View(content);
        }

        // GET: /Services/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            content content = db.contents.Find(id);
            if (content == null)
            {
                return HttpNotFound();
            }
            return View(content);
        }

        // POST: /Services/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, Authorize, ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,title,image,introtext,fulltext")] content content)
        {
            if (ModelState.IsValid)
            {
                string CurrentUser = null;
                if (System.Web.HttpContext.Current.Request.IsAuthenticated)
                {
                    CurrentUser = System.Web.HttpContext.Current.User.Identity.Name;
                }
                content.create_by = CurrentUser;
                content.catid = 3;
                db.Entry(content).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("ListService");
            }
            return View(content);
        }

        // GET: /Services/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            content content = db.contents.Find(id);
            if (content == null)
            {
                return HttpNotFound();
            }
            return View(content);
        }

        // POST: /Services/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            content content = db.contents.Find(id);
            db.contents.Remove(content);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult TopContent()
        {

            return PartialView(db.contents.Find(18));
        }
        public ActionResult LeftContent()
        {

            return PartialView(db.contents.Find(19));
        }
        public ActionResult RightContent()
        {

            return PartialView(db.contents.Find(20));
        }
    }
}

education/Views/Services/Create.cshtml
@model education.Models.content

@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    ViewBag.Title = "Create Service";
}
<style>
    .controls textarea {
        width: 80%;
        height: 70px;
    }
</style>
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jqueryval")
<script src="~/Scripts/ckfinder/ckfinder.js"></script>
<script src="~/Scripts/ckeditor/ckeditor.js" type="text/javascript"></script>
<script type="text/javascript">
    function BrowseServer() {
        var finder = new CKFinder();
        finder.selectActionFunction = SetFileField;
        finder.popup();
    }
    function SetFileField(fileUrl) {
        document.getElementById('image').value = fileUrl;
        document.getElementById('img').src = fileUrl;
    }
</script>
<div class="module">
    <div class="module-head">
        <h3>Service Manager</h3>
    </div>
    @using (Html.BeginForm("Create", "Services", FormMethod.Post, new { @class = "form-horizontal row-fluid" }))
    {
        <div class="module-body">
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            <div class="control-group">
                <label class="control-label" for="title">Title</label>
                <div class="controls">
                    @Html.TextBoxFor(model => model.title, new { @placeholder = "Type something here...", @class = "span8" })
                    @Html.ValidationMessageFor(model => model.title, null, new { @style = "color:red" })
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="imageinput">Image</label>
                <div class="controls">
                    @Html.TextBoxFor(model => model.image, new { @readonly = "readonly", @Value = "/content/images/nopicture.png" })
                    <input type="button" class="btn btn-default" value="Chọn Ảnh ..." onclick="BrowseServer();" id="imageinput" />
                    @Html.ValidationMessageFor(model => model.image)
                </div>
                <div class="controls">
                    <img src="~/content/images/nopicture.png" id="img" alt="" style="padding-top: 10px;width:190px;height:120px" />
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="introtext">IntroText</label>
                <div class="controls">
                    @Html.TextBoxFor(model => model.introtext, new { placeholder = "Type something here...", @class = "span8" })
                    @Html.ValidationMessageFor(model => model.note)
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="fulltext">FullText</label>
                <div class="controls">
                    @Html.TextAreaFor(model => model.fulltext, new { placeholder = "Type something here...", @class = "span8" })
                    <script type="text/javascript">
                    CKEDITOR.replace("fulltext");
                    </script>
                    @Html.ValidationMessageFor(model => model.note)
                </div>
            </div>
            <div class="control-group">
                <div class="controls">
                    <input type="submit" value="Create" class="btn btn-default" />

                    <input type="button" value="Back" class="btn btn-default" onclick="window.location.href = '/admin/service'" />
                </div>

            </div>
        </div>
    }
</div>

education/Views/Services/Delete.cshtml
@model education.Models.content

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>content</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.introtext)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.introtext)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fulltext)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fulltext)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.state)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.state)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.catid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.catid)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.created)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.create_by)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.create_by)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ordering)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ordering)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.hit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.hit)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

education/Views/Services/Details.cshtml
@model education.Models.content

@{
    ViewBag.Title = @Model.title;
}
<!-- Page Title -->
<div class="page-title-container">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 wow fadeIn">
                <i class="fa fa-arrow-right"></i>
                <h1>@Model.title /</h1>
                <p>@Model.introtext</p>
            </div>
        </div>
    </div>
</div>

<!-- About Us Text -->
<div class="about-us-container">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 about-us-text wow fadeInLeft">
                @*<img src="@Model.image">
                    <br />*@
                <p>@Html.Raw(Server.HtmlDecode(Model.fulltext))</p>
            </div>
        </div>
    </div>
</div>

education/Views/Services/Edit.cshtml
@model education.Models.content

@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    ViewBag.Title = "Edit Service";
}
<style>
    .controls textarea {
        width: 80%;
        height: 70px;
    }
</style>
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jqueryval")
<script src="~/Scripts/ckfinder/ckfinder.js"></script>
<script src="~/Scripts/ckeditor/ckeditor.js" type="text/javascript"></script>
<script type="text/javascript">
    function BrowseServer() {
        var finder = new CKFinder();
        finder.selectActionFunction = SetFileField;
        finder.popup();
    }
    function SetFileField(fileUrl) {
        document.getElementById('image').value = fileUrl;
        document.getElementById('img').src = fileUrl;
    }
</script>
<div class="module">
    <div class="module-head">
        <h3>Service Manager</h3>
    </div>
    @using (Html.BeginForm("Edit", "Services", FormMethod.Post, new { @class = "form-horizontal row-fluid" }))
    {
        <div class="module-body">
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            @Html.HiddenFor(model => model.id)
            <div class="control-group">
                <label class="control-label" for="title">Title</label>
                <div class="controls">
                    @Html.TextBoxFor(model => model.title, new { @placeholder = "Type something here...", @class = "span8" })
                    @Html.ValidationMessageFor(model => model.title, null, new { @style = "color:red" })
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="imageinput">Image</label>
                <div class="controls">
                    @Html.TextBoxFor(model => model.image, new { @readonly = "readonly", @Value = "/content/images/nopicture.png" })
                    <input type="button" class="btn btn-default" value="Chọn Ảnh ..." onclick="BrowseServer();" id="imageinput" />
                    @Html.ValidationMessageFor(model => model.image)
                </div>
                <div class="controls">
                    <img src="~/content/images/nopicture.png" id="img" alt="" style="padding-top: 10px;width:190px;height:120px" />
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="introtext">IntroText</label>
                <div class="controls">
                    @Html.TextBoxFor(model => model.introtext, new { placeholder = "Type something here...", @class = "span8" })
                    @Html.ValidationMessageFor(model => model.note)
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="fulltext">FullText</label>
                <div class="controls">
                    @Html.TextAreaFor(model => model.fulltext, new { placeholder = "Type something here...", @class = "span8" })
                    <script type="text/javascript">
                    CKEDITOR.replace("fulltext");
                    </script>
                    @Html.ValidationMessageFor(model => model.note)
                </div>
            </div>
            <div class="control-group">
                <div class="controls">
                    <input type="submit" value="Save" class="btn btn-default" />

                    <input type="button" value="Back" class="btn btn-default" onclick="window.location.href = '/admin/service'" />
                </div>

            </div>
        </div>
    }
</div>

education/Views/Services/Index.cshtml
@model IEnumerable<education.Models.content>

@{
    ViewBag.Title = "Tư vấn du học";
    string updownchecker = "fadeInUp";
}

        <!-- Page Title -->
<div class="page-title-container">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 wow fadeIn">
                <i class="fa fa-tasks"></i>
                <h1>Services /</h1>
                <p>Here are the services we offer</p>
            </div>
        </div>
    </div>
</div>

<!-- Services Full Width Text -->
<div class="services-full-width-container">
    <div class="container">
        <div class="row">
            @{Html.RenderAction("TopContent");}
        </div>
    </div>
</div>
<!-- Services -->
<div class="services-container">
    <div class="container">
        <div class="row">
            @foreach(var item in Model)
            {
                <div class="col-sm-3">
                    <div class="service wow @updownchecker">
                        <div class="service-icon"><i class="fa @item.image"></i></div>
                        <h3>@item.title</h3>
                        <p>@(Html.Raw(Server.HtmlDecode(@item.introtext)).ToString().Substring(0, 50)+"...")</p>
                        <a class="big-link-1" href="services/details/@item.id">Read more</a>
                    </div>
                </div>
                if (updownchecker == "fadeInUp")
                {
                    updownchecker = "fadeInDown";
                }
                else
                {
                    updownchecker = "fadeInUp";
                }
            }
        </div>
    </div>
</div>
<!-- Services Half Width Text -->
<div class="services-half-width-container">
    <div class="container">
        <div class="row">
            @{Html.RenderAction("LeftContent");}
            @{Html.RenderAction("RightContent");}
        </div>
    </div>
</div>
<!-- Call To Action -->
<div class="call-to-action-container">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 call-to-action-text wow fadeInLeftBig">
                <p>
                    Lorem ipsum <span class="violet">dolor sit amet</span>, consectetur adipisicing elit,
                    sed do eiusmod tempor incididunt ut labore et ut wisi.
                </p>
                <div class="call-to-action-button">
                    <a class="big-link-3" href="contact">Sign Up Now!</a>
                </div>
            </div>
        </div>
    </div>
</div>

education/Views/Services/LeftContent.cshtml
@model education.Models.content

<div class="col-sm-6 services-half-width-text wow fadeInLeft">
    <h3>@Model.title</h3>
    <p>
        @Html.Raw(Server.HtmlDecode(Model.introtext))
    </p>
</div>

education/Views/Services/ListService.cshtml
@model IEnumerable<education.Models.content>

@{
    ViewBag.Title = "ListService";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<script>
    function OnDeleteClick(e) {

        var flag = confirm('You are about to delete serviee ID ' + e + ' permanently.Are you sure you want to delete this record?');

        if (flag) {

            $.ajax({

                url: '/Services/DeleteService',

                type: 'POST',

                data: { id: e },

                dataType: 'json',

                success: function (result) {
                    alert(result);
                    $("#" + e).parent().parent().remove();
                },

                error: function () { alert('Error!'); }

            });

        }

        return false;

    }
</script>
<div class="module">
    <div class="module-head">
        <h3>Quản lý service</h3>
    </div>
    <div class="module-body">

        <p>
            <strong>Thêm service</strong>
        </p>
        <div class="controls">
            <button type="button" class="btn" onclick="window.location.href = '/admin/service/create'">New</button>
            <!--<button type='submit' name='btn1' class="btn">Edit</button>
            <button type='submit' name='btn2' class="btn" onclick="return DelProduct();">Delete</button>-->
            <br />
            <br />
            <table class="table table-striped table-bordered table-condensed">
                <thead>
                    <tr>
                        <th>Title</th>
                        <th>Introtext</th>
                        <th>Created By</th>
                        <th width="15%">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var row in Model)
                    {
                        <tr>
                            <td> @row.title</td>
                            <td> <div style="white-space: nowrap; width: 18em; overflow: hidden;text-overflow: ellipsis;">@row.introtext</div></td>
                            <td> @row.create_by</td>
                            <td>
                                <button type="button" class="btn" onclick="window.location.href = '/admin/service/edit/@row.id'">Edit</button>
                                <button type="button" class="btn" onclick="return OnDeleteClick(@row.id);" id="@row.id">Delete</button>

                            </td>
                        </tr>
                    }

                </tbody>
            </table>
        </div>
    </div>
</div>

education/Views/Services/RightContent.cshtml
@model education.Models.content

<div class="col-sm-6 services-half-width-text wow fadeInUp">
    <h3>@Model.title</h3>
    <p>
        @Html.Raw(Server.HtmlDecode(Model.introtext))
    </p>
</div>

education/Views/Services/TopContent.cshtml
@model education.Models.content

<div class="col-sm-12 services-full-width-text wow fadeInLeft">
    <h3>@Model.title</h3>
    <p>
        @Html.Raw(Server.HtmlDecode(Model.introtext))
    </p>
</div>